version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8-jdk
    working_directory: ~/ceri-m1-techniques-de-test
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: mvn test
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Upload to Codecov
          command: bash <(curl -s https://codecov.io/bash) -t ${CODECOV_TOKEN}
