version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Run Unit Tests and Generate Coverage Report
          command: mvn clean verify # 'verify' phase will run after 'test' and can be configured to generate reports
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Upload Coverage to Codecov
          command: |
            bash <(curl -s https://codecov.io/bash) -v -f target/site/jacoco/jacoco.xml -t ${CODECOV_TOKEN}

workflows:
  version: 2
  build_and_report:
    jobs:
      - build
