version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk  # Utilisation d'une image Docker avec Java 8

    working_directory: ~/repo

    steps:
      - checkout  # Récupération du code du repository

      # Exécution des tests unitaires avec Maven
      - run:
          name: Run Unit Tests
          command: mvn test

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master  # Exécution sur la branche master uniquement
