version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/ceri-m1-techniques-de-test
    steps:
      - checkout
      - run:
          name: Tests unitaires
          command: mvn test
      - run:
          name: Generation de ma javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Verification du checkstyle
          command: mvn checkstyle:check
      - persist_to_workspace:
          root: ~/ceri-m1-techniques-de-test
          paths:
            - target/site/apidocs

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Add GitHub to Known Hosts
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan -H github.com >> ~/.ssh/known_hosts
      - run:
          name: Deploiement du javadoc sur github-pages
          command: |
            set -e  # Stop on error
            git config --global user.name "$GH_NAME"
            git config --global user.email "$GH_EMAIL"
            # Ensure the .git URL format for cloning
            REPO_URL=$(echo $CIRCLE_REPOSITORY_URL | sed 's/https:\/\/\(.*\):\(.*\)@/https:\/\/\1\/\2.git/')
            git clone $CIRCLE_REPOSITORY_URL ~/git-ceri-m1-techniques-de-test
            cd ~/git-ceri-m1-techniques-de-test
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .
            cp -r ~/repo/target/site/apidocs/* .
            git add --all
            git commit -m "Deploy Javadoc [skip ci]" || echo "No changes to commit"
            git push origin gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build