version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/ceri-m1-techniques-de-test

    steps:
      - checkout

      - run:
          name: Run Unit Tests
          command: mvn test
          
workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            branches:
              only: master
