version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/ceri-m1-techniques-de-test
    steps:
      - checkout
      - run:
          name: Run Unit Tests
          command: mvn test
      - run:
          name: Generate Javadoc
          command: mvn javadoc:javadoc
      - persist_to_workspace:
          root: ~/ceri-m1-techniques-de-test
          paths:
            - target/site/apidocs
          
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy Javadoc to GitHub Pages
          command: |
            git config user.name "$GH_NAME"
            git config user.email "$GH_EMAIL"
            git clone $CIRCLE_REPOSITORY_URL git-repo
            cd git-repo
            git checkout gh-pages || git checkout --orphan gh-pages
            git rm -rf .
            cp -r /tmp/workspace/target/site/apidocs/* .
            git add .
            git commit -m "Deploy Javadoc [skip ci]"
            git push origin gh-pages

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
