name: Java CI with Maven

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Build and generate Javadoc
      run: mvn clean javadoc:javadoc

    - name: Checkstyle
      run: mvn checkstyle:checkstyle

    - name: Publish Javadoc to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/site/apidocs
