version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2
    working_directory: ~/ceri-m1-techniques-de-test
    steps:
      - checkout
      - run:
          name: Tests unitaires et rapport de couverture
          command: mvn clean test jacoco:report
      - run: 
          name: Generation de la javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Publication du code coverage
          command: |
            echo 'export CODECOV_TOKEN="${CODECOV_TOKEN}"' >> $BASH_ENV
            source $BASH_ENV
            bash <(curl -s https://codecov.io/bash)
      - persist_to_workspace:
          root: ~/ceri-m1-techniques-de-test
          paths:
            - target/site/apidocs

workflows:
  build_and_deploy:
    jobs:
      - build
