version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/ceri-m1-techniques-de-test
    steps:
      - checkout
      - run:
          name: Tests unitaires
          command: mvn test
      - run:
          name: Generation de ma javadoc
          command: mvn javadoc:javadoc
      - run:
          name: Verification du checkstyle
          command: mvn checkstyle:check
      - persist_to_workspace:
          root: ~/ceri-m1-techniques-de-test
          paths:
            - target/site/apidocs

  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/ceri-m1-techniques-de-test
    steps:
      - attach_workspace:
          at: ~/ceri-m1-techniques-de-test
      - run:
          name: Install and configure dependencies
          command: |
            sudo npm install -g gh-pages
            git config user.email "your_email@example.com"
            git config user.name "Your Name"
      - add_ssh_keys:
          fingerprints:
            - "your:fingerprint:here"  
      - run:
          name: Deploy docs to gh-pages branch
          command: |
            gh-pages --dotfiles --message "[skip ci] Updates" --dist ~/ceri-m1-techniques-de-test/target/site/apidocs

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
