version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2
    working_directory: ~/ceri-m1-techniques-de-test
    steps:
      - checkout
      - run:
          name: Tests unitaires
          command: mvn test
      - run:
          name: Generation de ma javadoc
          command: mvn javadoc:javadoc
      - persist_to_workspace:
          root: ~/ceri-m1-techniques-de-test
          paths:
            - target/site/apidocs

workflows:
  build:
    jobs:
      - build
