version: 2.1

jobs:
  build:
    docker:
      - image: cimg/openjdk:21.0.2
    working_directory: ~/ceri-m1-techniques-de-test
    steps:
      - checkout
      - run:
          name: Tests unitaires
          command: mvn test
      - run:
          name: Generation de ma javadoc
          command: mvn javadoc:javadoc
      - persist_to_workspace:
          root: ~/ceri-m1-techniques-de-test
          paths:
            - target/site/apidocs

  deploy:
    docker:
      - image: cimg/openjdk:21.0.2-node
    working_directory: ~/ceri-m1-techniques-de-test
    steps:
      - attach_workspace:
          at: ~/ceri-m1-techniques-de-test
      - run:
          name: Installation et dependances
          command: |            
            sudo npm install -g npm@10.5.1
            
      - run:
          name: Deploiement de la documentation
          command: |
            sudo npm install -g --silent gh-pages@6.1.1
            git config user.email "abakarjunior077@gmail.com"
            git config user.name "juniorabakar"
      - add_ssh_keys:
          fingerprints:
            - "SHA256:ktWCeOf4ZTM0Rg6wbpcvQ/s4FHSK71PG81+w9oQTm0I"
workflows:
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
