name: Deploy Javadoc to GitHub Pages

on:
  push:
    branches: [ master ]  # Trigger on pushes to master branch

jobs:
  deploy-javadoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2  # Check out the repository code

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'  # Use AdoptOpenJDK

      - name: Generate Javadoc
        run: mvn javadoc:javadoc  # Run Maven Javadoc generation

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the GITHUB_TOKEN secret for authentication
          publish_dir: ./target/site/apidocs  # Directory where Javadoc is generated
