name: Build et déploiement

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'master'

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build et generation des rapports
      run: |
        mvn -B checkstyle:checkstyle
        mvn -B javadoc:javadoc
        git config --global user.name 'juniorabakar'
        git config --global user.email 'abakarjunior077@gmail.com'
        git stash push -m "Sauvegarde temporaire des modifications"


    - name: Cloner la branche gh-pages pour le déploiement
      run: |
        git config --global user.name 'juniorabakar'
        git config --global user.email 'abakarjunior077@gmail.com'
        git fetch --no-tags --prune --depth=1 origin +refs/heads/gh-pages:refs/remotes/origin/gh-pages
        git checkout gh-pages
        git rm -r '*'
        cp -r target/site/* .
        git add .
        git commit -m "Deploy updated reports to GitHub Pages"
        git push origin gh-pages
